### PR TITLE
Allow users to add new prompt for different sites

### PR DESCRIPTION
**Pull request by joonhok-fittube**
These are how the new change look

Screen Shot 2023-02-10 at 10 22 29 PM
Screen Shot 2023-02-10 at 10 22 42 PM
Screen Shot 2023-02-10 at 10 23 22 PM
Screen Shot 2023-02-10 at 10 24 20 PM

### CODE REVIEW

**Comment by hunkim** [comment]
Wonderful!!

```
const siteName = location.hostname.match(siteRegex)![0]
```
Can you check this and follow the site name convention? So when people type `https://xxx.arxiv.com/lkok` we automatically replace it with `arxiv` to avoid any confusion?

**Comment by joonhok-fittube** [comment]
> Wonderful!!
> 
> ```
> const siteName = location.hostname.match(siteRegex)![0]
> ```
> 
> Can you check this and follow the site name convention? So when people type `https://xxx.arxiv.com/lkok` we automatically replace it with `arxiv` to avoid any confusion?

@hunkim Sure, let me have a look.

**Comment by joonhok-fittube** [comment]
@hunkim It looks the current site name convention is not very robust and extensible. It blindly takes the first part of the hostname and drop the remaining part. For example, `https://arxiv.org/`'s hostname is `arxiv.org`, and the code snippet returns `arxiv`. But there are a couple of cases when this approach may break, 

Case 1: people may want to set different prompts for different hostnames that happen to have the same first part of the hostname. For example, `google.com` and `google.co.kr`.
Case 2: taking the first part of the hostname blindly and using it as an ID is not robust. `ai.googleblog.com`, `research.google`, and so on.

I think the full hostname should be the identifier of a custom prompt. What do you think?

**Comment by hunkim** [comment]
OK. Let's do that. merged. Thanks!

**Pull request merged**
