### PR TITLE
add support for IEEE Xplore and PubMed 

### PR DESCRIPTION
**Pull request by yeeeqichen**
#13 
Preview for PubMed: 
image

Preview for IEEE Xplore:

image

### CODE REVIEW

**Comment by hunkim** [comment]
Looks good to me. I will merge. 

However, do you tink you can add this to our configuration? Like adding per site prompt, we can add siteurl, body, and display tags in the configuration. It would be wonderful.

Please consult @joonhok-fittube who added site prompts or his code.

**Comment by yeeeqichen** [comment]
> Looks good to me. I will merge.
> 
> However, do you tink you can add this to our configuration? Like adding per site prompt, we can add siteurl, body, and display tags in the configuration. It would be wonderful.
> 
> Please consult @joonhok-fittube who added site prompts or his code.

Sure! I'll keep working on it

**Comment by joonhok-fittube** [comment]
Let me know if you need my help!

**Comment by cmosguy** [comment]
@hunkim  is it possible to test this out?  I am only see version `2023.2.14` in the extension information.

**Comment by joonhok-fittube** [comment]
@cmosguy 
You can test it by cloning this repo and run it in your local. Steps to run it:

1. Run `npm install`
2. Run `npm run build`
3. Go to "chrome://extensions/", then enable "Developer mode".
4. Click "Load unpacked". Select chatgpt-arxiv-extension > build > chromium directory.

Then you will be able to test new feature on your local machine. Let me know if you have any question.

**Comment by cmosguy** [comment]
@joonhok-fittube  thank you so much for the help here!! That worked.  BTW, I do not mean to hijack this topic, but where in this code base does it actually read in the content from the HTML/PDF and feed it into chatgpt for summarization?  I am trying to learn more how this works.  Essentially, I am trying to understand how the payload is munged and sent to chatgpt.

**Pull request merged**
